#!/bin/bash

# --- 1. 初始化数据库 ---
# 使用 init.sql 重置数据库 (会执行 DROP TABLE)
# 密码 114514 来自 core/config.py
echo "[*] Resetting Database..."
mysql -u root -p114514 < dao/init.sql

# --- 2. 注册并登录 ---
echo "[*] Registering User..."
python cli.py user register admin admin123

echo "[*] Logging in..."
python cli.py user login admin admin123

# --- 3. 创建第一篇文章 ---
# 捕获输出中的 CID (格式: "Post created. CID: <cid>")
CID1=$(python cli.py post create | awk '{print $4}')
echo "[+] Created Post 1 CID: $CID1"

# 更新元数据
python cli.py post update $CID1 title "Hello MegaCite"
python cli.py post update $CID1 catagory "Intro"
python cli.py post update $CID1 description "First blog post"
# 更新正文 (使用 \n\n 表示换行)
python cli.py post update $CID1 context "# Welcome\n\nThis is the **first** post generated by CLI.\n\nIt supports Markdown!"

# --- 4. 创建第二篇文章 ---
CID2=$(python cli.py post create | awk '{print $4}')
echo "[+] Created Post 2 CID: $CID2"

python cli.py post update $CID2 title "Markdown Features"
python cli.py post update $CID2 catagory "Docs"
python cli.py post update $CID2 context "## List Test\n\n- Feature A\n- Feature B\n\n> \`Code\` is poetry.\n\n<http://127.0.0.1:8080/admin/Intro/Hello-MegaCite.html>"

# --- 5. 启动服务器 ---
echo "[*] Starting Server on port 8080..."
# 这一步会阻塞终端，按 Ctrl+C 停止
python cli.py server start 8080